// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *publication → content*
 */
export interface PublicationDocumentDataContentItem {
  /**
   * heading field in *publication → content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: publication.content[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * body field in *publication → content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: publication.content[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Content for publication documents
 */
interface PublicationDocumentData {
  /**
   * title field in *publication*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: publication.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *publication*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: publication.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * author field in *publication*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: publication.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * banner field in *publication*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: publication.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>;

  /**
   * content field in *publication*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: publication.content[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<Simplify<PublicationDocumentDataContentItem>>;
}

/**
 * publication document from Prismic
 *
 * - **API ID**: `publication`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PublicationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PublicationDocumentData>,
    'publication',
    Lang
  >;

export type AllDocumentTypes = PublicationDocument;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PublicationDocument,
      PublicationDocumentData,
      PublicationDocumentDataContentItem,
      AllDocumentTypes,
    };
  }
}
